### ISSUE TITLE
[BUG] Notification plugin hangs at PluginBaseAction class

### ISSUE THREAD

**Issue by lezzago** [opensearch-project/notifications#233]
**Describe the bug**
When I call the GetNorificationConfig API for channels that do not exist. I get an error like below. And if I call CreateNotificationConfig API for the channels that did not exist, the code hangs at this [line](https://github.com/opensearch-project/notifications/blob/develop/notifications/src/main/kotlin/org/opensearch/notifications/action/PluginBaseAction.kt#L78).
```
[2021-07-19T21:17:27,047][ERROR][o.o.b.OpenSearchUncaughtExceptionHandler] [3c22fbe8fc7e.ant.amazon.com] uncaught exception in thread [DefaultDispatcher-worker-1]
org.opensearch.OpenSearchStatusException: NotificationConfig [GYcdwnoBFdGdFG5MPAzu, GocdwnoBFdGdFG5MVAw1, GIcdwnoBFdGdFG5MDgx3] not found
	at org.opensearch.notifications.index.ConfigIndexingActions.info(ConfigIndexingActions.kt:297) ~[opensearch-notifications-1.0.0.jar:1.0.0]
	at org.opensearch.notifications.index.ConfigIndexingActions.get(ConfigIndexingActions.kt:254) ~[opensearch-notifications-1.0.0.jar:1.0.0]
	at org.opensearch.notifications.action.GetNotificationConfigAction.executeRequest(GetNotificationConfigAction.kt:82) ~[opensearch-notifications-1.0.0.jar:1.0.0]
	at org.opensearch.notifications.action.GetNotificationConfigAction.executeRequest(GetNotificationConfigAction.kt:48) ~[opensearch-notifications-1.0.0.jar:1.0.0]
	at org.opensearch.notifications.action.PluginBaseAction$doExecute$1.invokeSuspend(PluginBaseAction.kt:80) ~[opensearch-notifications-1.0.0.jar:1.0.0]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) [kotlin-stdlib-1.4.32.jar:1.4.32-release-371 (1.4.32)]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) [kotlinx-coroutines-core-jvm-1.4.3.jar:?]
```

**To Reproduce**
Call getNotificationConfig API for a non-existent channel and then try create a channel

**Expected behavior**
Notification should catch the exception and return empty response or catch and throw NotFoundException instead.

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

**Comment by lezzago** [comment]
This appears to be fixed after pulling in latest changes from common-utils and the testing branch for notification
