### ISSUE TITLE
Build fail due to github action for NotificationEventIndexTests

### ISSUE THREAD

**Issue by kavithacm** [opensearch-project/notifications#319]
The build for notification project is successful and all the test cases passed in the local env setup. Due to some github action, when NotificationEventIndexTests file is included in the build, the build fails for the NotificationEventDocTests. I have included some of the logs of the build fail for reference. 

Error logs:
```
> Task :notifications:test
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended



Suite: Test class org.opensearch.notifications.model.NotificationEventDocTests
  2> org.opentest4j.AssertionFailedError: expected: <NotificationEventDoc(metadata=DocMetadata(lastUpdateTime=2021-09-10T18:24:33.494Z, createdTime=2021-09-10T18:07:53.494Z, tenant=selectedTenant, access=[User:user, Role:sample_role, BERole:sample_backend_role]), event=NotificationEvent(eventSource=EventSource(title=title, referenceId=reference_id, feature=alerting, severity=info, tags=[tag1, tag2]), statusList=[EventStatus(configId=config_id, configName=name, configType=chime, emailRecipientStatus=[], deliveryStatus=DeliveryStatus(statusCode=200, statusText=success))]))> but was: <NotificationEventDoc(metadata=DocMetadata(lastUpdateTime=2021-09-10T18:24:33.214Z, createdTime=2021-09-10T18:07:53.214Z, tenant=tenant, access=[User:user, Role:sample_role, BERole:sample_backend_role]), event=NotificationEvent(eventSource=EventSource(title=title, referenceId=reference_id, feature=alerting, severity=info, tags=[tag1, tag2]), statusList=[EventStatus(configId=config_id, configName=name, configType=chime, emailRecipientStatus=[], deliveryStatus=DeliveryStatus(statusCode=200, statusText=success))]))>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
        at org.opensearch.notifications.model.NotificationEventDocTests.Event doc should safely ignore extra field in json object(NotificationEventDocTests.kt:135)
  2> org.opentest4j.AssertionFailedError: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:71)
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
        at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3007)
        at org.opensearch.notifications.model.NotificationEventDocTests.Event doc should throw exception if metadata is absent in json(NotificationEventDocTests.kt:165)
  2> org.opentest4j.AssertionFailedError: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:71)
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
        at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3007)
        at org.opensearch.notifications.model.NotificationEventDocTests.Event doc should throw exception if event is absent in json(NotificationEventDocTests.kt:184)
  2> org.opentest4j.AssertionFailedError: expected: <NotificationEventDoc(metadata=DocMetadata(lastUpdateTime=2021-09-10T18:24:33.519Z, createdTime=2021-09-10T18:07:53.519Z, tenant=tenant, access=[User:user, Role:sample_role, BERole:sample_backend_role]), event=NotificationEvent(eventSource=EventSource(title=title, referenceId=reference_id, feature=alerting, severity=info, tags=[tag1, tag2]), statusList=[EventStatus(configId=config_id, configName=name, configType=chime, emailRecipientStatus=[], deliveryStatus=DeliveryStatus(statusCode=200, statusText=success))]))> but was: <NotificationEventDoc(metadata=DocMetadata(lastUpdateTime=2021-09-10T18:24:33.214Z, createdTime=2021-09-10T18:07:53.214Z, tenant=tenant, access=[User:user, Role:sample_role, BERole:sample_backend_role]), event=NotificationEvent(eventSource=EventSource(title=title, referenceId=reference_id, feature=alerting, severity=info, tags=[tag1, tag2]), statusList=[EventStatus(configId=config_id, configName=name, configType=chime, emailRecipientStatus=[], deliveryStatus=DeliveryStatus(statusCode=200, statusText=success))]))>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
        at org.opensearch.notifications.model.NotificationEventDocTests.Event doc serialize and deserialize using json config object should be equal(NotificationEventDocTests.kt:72)
org.opensearch.notifications.model.NotificationEventDocTests > Event doc should safely ignore extra field in json object() FAILED
    org.opentest4j.AssertionFailedError: expected: <NotificationEventDoc(metadata=DocMetadata(lastUpdateTime=2021-09-10T18:24:33.494Z, createdTime=2021-09-10T18:07:53.494Z, tenant=selectedTenant, access=[User:user, Role:sample_role, BERole:sample_backend_role]), event=NotificationEvent(eventSource=EventSource(title=title, referenceId=reference_id, feature=alerting, severity=info, tags=[tag1, tag2]), statusList=[EventStatus(configId=config_id, configName=name, configType=chime, emailRecipientStatus=[], deliveryStatus=DeliveryStatus(statusCode=200, statusText=success))]))> but was: <NotificationEventDoc(metadata=DocMetadata(lastUpdateTime=2021-09-10T18:24:33.214Z, createdTime=2021-09-10T18:07:53.214Z, tenant=tenant, access=[User:user, Role:sample_role, BERole:sample_backend_role]), event=NotificationEvent(eventSource=EventSource(title=title, referenceId=reference_id, feature=alerting, severity=info, tags=[tag1, tag2]), statusList=[EventStatus(configId=config_id, configName=name, configType=chime, emailRecipientStatus=[], deliveryStatus=DeliveryStatus(statusCode=200, statusText=success))]))>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
        at org.opensearch.notifications.model.NotificationEventDocTests.Event doc should safely ignore extra field in json object(NotificationEventDocTests.kt:135)

org.opensearch.notifications.model.NotificationEventDocTests > Event doc should throw exception if metadata is absent in json() FAILED
    org.opentest4j.AssertionFailedError: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:71)
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
        at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3007)
        at org.opensearch.notifications.model.NotificationEventDocTests.Event doc should throw exception if metadata is absent in json(NotificationEventDocTests.kt:165)

org.opensearch.notifications.model.NotificationEventDocTests > Event doc should throw exception if event is absent in json() FAILED
    org.opentest4j.AssertionFailedError: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown.
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:71)
        at org.junit.jupiter.api.AssertThrows.assertThrows(AssertThrows.java:37)
        at org.junit.jupiter.api.Assertions.assertThrows(Assertions.java:3007)
        at org.opensearch.notifications.model.NotificationEventDocTests.Event doc should throw exception if event is absent in json(NotificationEventDocTests.kt:184)

org.opensearch.notifications.model.NotificationEventDocTests > Event doc serialize and deserialize using json config object should be equal() FAILED
    org.opentest4j.AssertionFailedError: expected: <NotificationEventDoc(metadata=DocMetadata(lastUpdateTime=2021-09-10T18:24:33.519Z, createdTime=2021-09-10T18:07:53.519Z, tenant=tenant, access=[User:user, Role:sample_role, BERole:sample_backend_role]), event=NotificationEvent(eventSource=EventSource(title=title, referenceId=reference_id, feature=alerting, severity=info, tags=[tag1, tag2]), statusList=[EventStatus(configId=config_id, configName=name, configType=chime, emailRecipientStatus=[], deliveryStatus=DeliveryStatus(statusCode=200, statusText=success))]))> but was: <NotificationEventDoc(metadata=DocMetadata(lastUpdateTime=2021-09-10T18:24:33.214Z, createdTime=2021-09-10T18:07:53.214Z, tenant=tenant, access=[User:user, Role:sample_role, BERole:sample_backend_role]), event=NotificationEvent(eventSource=EventSource(title=title, referenceId=reference_id, feature=alerting, severity=info, tags=[tag1, tag2]), statusList=[EventStatus(configId=config_id, configName=name, configType=chime, emailRecipientStatus=[], deliveryStatus=DeliveryStatus(statusCode=200, statusText=success))]))>
        at org.junit.jupiter.api.AssertionUtils.fail(AssertionUtils.java:55)
        at org.junit.jupiter.api.AssertionUtils.failNotEqual(AssertionUtils.java:62)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:182)
        at org.junit.jupiter.api.AssertEquals.assertEquals(AssertEquals.java:177)
        at org.junit.jupiter.api.Assertions.assertEquals(Assertions.java:1124)
        at org.opensearch.notifications.model.NotificationEventDocTests.Event doc serialize and deserialize using json config object should be equal(NotificationEventDocTests.kt:72)


27 tests completed, 4 failed
Tests with failures:
 - org.opensearch.notifications.model.NotificationEventDocTests.Event doc should safely ignore extra field in json object()
 - org.opensearch.notifications.model.NotificationEventDocTests.Event doc should throw exception if metadata is absent in json()
 - org.opensearch.notifications.model.NotificationEventDocTests.Event doc should throw exception if event is absent in json()
 - org.opensearch.notifications.model.NotificationEventDocTests.Event doc serialize and deserialize using json config object should be equal()

> Task :notifications:test FAILED


Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.6.1/userguide/command_line_interface.html#sec:command_line_warnings
22 actionable tasks: 22 executed
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':notifications:test'.
> There were failing tests. See the report at: file:///home/runner/work/notifications/notifications/notifications/notifications/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 35s
Error: Process completed with exit code 1.
```

To overcome this issue and merge the NotificationEventIndexTests file, a modification is to be made to the notification-test-and-build-workflow.yml. The highlighted line from the following file should be modified to the following command to exclude the NotificationEventIndexTests temporarily to build the notification project.

File and the command to be modified: https://github.com/opensearch-project/notifications/blob/88b62178185c497e78a486926983536fc2259a1c/.github/workflows/notifications-test-and-build-workflow.yml#L73

Command: `./gradlew build -PexcludeTests="**/SesChannelIT*" -PexcludeTests="**/NotificationEventIndexTests*" -Dopensearch.version=${{ env.OPENSEARCH_VERSION }}`

**Comment by qreshi** [comment]
Closing this issue since `NotificationEventIndexTests` and `NotificationEventDocTests` are no longer present.
